//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	/// <summary>
	/// card level
	/// </summary>
	public enum RX_CARD_LEVEL
	{
		RX_LEVEL_3 = 3,
		RX_LEVEL_4 = 4,
		RX_LEVEL_5 = 5,
		RX_LEVEL_6 = 6,
		RX_LEVEL_7 = 7,
		RX_LEVEL_8 = 8,
		RX_LEVEL_9 = 9,
		RX_LEVEL_0 = 10,
		RX_LEVEL_J = 11,
		RX_LEVEL_Q = 12,
		RX_LEVEL_K = 13,
		RX_LEVEL_A = 14,
		RX_LEVEL_2 = 15,
		RX_LEVEL_S = 16,
		RX_LEVEL_B = 17
	}

	public enum RX_CARD_NAME
	{
		//hong tao
		RX_NAME_HOT = 0,
		//fang pian
		RX_NAME_FAP = 1,
		//hei tao
		RX_NAME_HET = 2,
		//maei hua
		RX_NAME_MEH = 3,
		//king
		RX_NAME_KIN = 4
	}


		public class RX_Define
		{
		#region Singleton
				// private constructor
				private RX_Define ()
				{
				}
				// Creat static variable s_RX_Define
				private static RX_Define s_RX_Define = null;
				
				//Creat static property function DefaultDefine
				public static RX_Define DefaultDefine {
						get {
								if (s_RX_Define == null) {
										s_RX_Define = new RX_Define ();
								}
								return s_RX_Define;
						}
				}
		#endregion
		//Creat Card Count Variables...
		public const int RX_Card_Number = 54;

		//hong tao
		public const int RX_HOT_Number = 0;

		//fang pian
		public const int RX_FAP_Number = 13;

		//hei tao
		public const int RX_HET_Number = 26;

		//mei hua
		public const int RX_MEH_Number = 39;

		//xiao wang
		public const int RX_SMA_Number = 52;

		//da wang
		public const int RX_BIG_Number = 53;

		}
		
}

